app/models.py
from . import db
from  werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    email= db.Column(db.String(255),unique=True,index=True)
    password = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_picture = db.Column(db.String(255))
    date_joined = db.Column(db.DateTime(250), default=datetime.utcnow)
    asset = db.relationship('Asset', backref='user', lazy='dynamic')
    
    
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'
     
     
class Asset(db.Model):
    __tablename__ = 'assets'
    
    id = db.Column(db.Integer, primary_key=True)
    assetname = db.Column(db.String(255))
    category_id = db.Column(db.String(255), nullable=False)
    description = db.Column(db.String(), index = True)
    worth= db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'),nullable=False)
    date_posted = db.Column(db.DateTime(250), default=datetime.utcnow)
    
    
    
    
    def save_assets(self):
        db.session.add(self)
        db.session.commit()
        
    def delete(self):
        db.session.delete(self)
        db.session.commit()
    
    @classmethod
    def get_assets(cls):
        assets = Asset.query.filter_by(assets_id=id).all()
        return assets

    def __repr__(self):
        return f"Asset {self.assetname}"
    
    
    
    
    
class Subscriber(db.Model):
    __tablename__='subscribers'

    id=db.Column(db.Integer,primary_key=True)
    email = db.Column(db.String(255),unique=True,index=True)

    def save_subscriber(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'Subscriber {self.email}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField,SelectField, IntegerField, PasswordField,BooleanField
from wtforms.validators import InputRequired ,Email,EqualTo
from wtforms import ValidationError

    

class AssetForm(FlaskForm):
    title = StringField('Title', validators=[InputRequired()])
    description =TextAreaField('How best would you describe your Asset?', validators=[InputRequired()])
    worth = IntegerField('worth', validators=[InputRequired()])
    category_id = SelectField('Label', choices=[('currentAssets','Current Assets'),('financialAssets', 'Financial Assets'),('fixedAssets','Fixed Assets')])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
# from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail
# from flask_simplemde import SimpleMDE
from flask_sqlalchemy import SQLAlchemy
from config import config_options

login_manager = LoginManager()

login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()



db = SQLAlchemy()
# photos = UploadSet('photos', IMAGES)
mail=Mail()
# simple = SimpleMDE()


def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    # simple.init_app(app)

    # configure_uploads(app, photos)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    
    
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template, redirect, url_for, flash, Flask, make_response, request
from . import main
from ..models import Asset, User, Subscriber
from .forms import AssetForm
from flask_login import login_required, current_user
from app import db, create_app
from ..email import mail_message
import pdfkit 

create_app = Flask(__name__)


@main.route('/report_<name>.pdf')
def report_pdf():
    # Make a PDF straight from HTML in a string.
    html = render_template('comments.html', name=name)
    pdf = pdfkit.from_string(html, False)
    response = make_response(pdf) 
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition']='inline; filename=output.pdf'  
    return  response



@main.route('/')
@main.route('/home')
def index():

    return render_template('index.html')


@main.route('/dashboard/index')
@login_required
def user_dash():

    return render_template('dash2.html')

@main.route('/assets/')
@login_required
def asset():
    title = 'assets'
    assets = Asset.query.filter_by().first()
    currentAssets = Asset.query.filter_by(category_id='currentAssets')
    financialAssets = Asset.query.filter_by(category_id='financialAssets')
    fixedAssets = Asset.query.filter_by(category_id='fixedAssets')

    return render_template('assets.html', assets=assets, title=title, currentAssets=currentAssets, financialAssets=financialAssets, fixedAssets=fixedAssets)


@main.route('/assets/<int:user_id>/new', methods=['GET', 'POST'])
@login_required
def assets_new(user_id):
    form = AssetForm()
    if form.validate_on_submit():
        description = form.description.data
        assetname = form.assetname.data
        category_id = form.category_id.data
        worth = form.worth.data
        location = form.location.data
        new_asset = Asset(user_id=user_id, assetname=assetname,
                          description=description, category_id=category_id, worth=worth, location=location)
        new_asset.save_assets()
        flash('Your asset has been added successfully', 'success')
        return redirect(url_for('main.view', user_id=user_id))
    return render_template('new_asset.html', form=form)


@main.route('/tables')
@login_required
def view():
    posts = Asset.query.all()
    
    return render_template('tables.html', posts=posts)

@main.route("/location")
@login_required
def location():

    return render_template("locations.html")

@main.route('/subscribe',methods = ['POST','GET'])
def subscribe():
    email = request.form.get('subscriber')
    new_subscriber = Subscriber(email = email)
    new_subscriber.save_subscriber()
    mail_message("Subscribed to M-thamini","email/welcome_user",new_subscriber.email,new_subscriber=new_subscriber)
    flash('Successfully subscribed')
    return redirect(url_for('main.index'))

app/templates/base_dash.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="Nimrod Musungu, Victor Makori, April Wairimu" />
    <link rel="shortcut icon" href="{{url_for('static', filename='images/logo/favicon.png')}}" type="image/x-icon">

    <title>M-Thamini - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link
      href="{{url_for('static', filename='vendor/fontawesome-free/css/all.min.css')}}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="{{url_for('static', filename='css/sb-admin-2.min.css')}}" rel="stylesheet" />
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}" />
  </head>

  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      <ul
        class="navbar-nav sidenav sidebar sidebar-dark accordion"
        id="accordionSidebar"
      >
        <!-- Sidebar - Brand -->
        <a
          class="sidebar-brand d-flex align-items-center justify-content-center"
          href="{{url_for('main.index')}}"
        >
          <div class="sidebar-brand-text mx-3">
            <img src="{{url_for('static', filename='images/logo/logo-white.png')}}" alt="" style="max-height: 30px" />
          </div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0" />

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('main.user_dash')}}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a
          >
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider" />

        <!-- Heading -->
        <div class="sidebar-heading">Interface</div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
          <a
            class="nav-link collapsed"
            href="{{url_for('main.assets_new',user_id=current_user.id)}}"
            data-toggle="collapse"
            data-target="#collapseTwo"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-plus"></i>
            <span class="xyz">Add Assets</span>
          </a>
          
        </li>

        <!-- Nav Item - Utilities Collapse Menu -->
        <li class="nav-item">
          <a
            class="nav-link collapsed"
            href="#"
            data-toggle="collapse"
            data-target="#collapseUtilities"
            aria-expanded="true"
            aria-controls="collapseUtilities"
          >
            <i class="fas fa-fw fa-notes-medical"></i>
            <span>Valuation</span>
          </a>
          
        </li>
        <li class="nav-item">
          <a
            class="nav-link collapsed"
            href="{{url_for('main.location')}}"
          >
            <i class="fas fa-location-arrow"></i>
            <span class="loc-maps">Assets Locations</span>
          </a>
          
        </li>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span></a
          >
        </li>

        <!-- Nav Item - Tables -->
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.view',username = current_user.username)}}">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a
          >
          
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block" />

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
      </ul>
      <!-- End of Sidebar -->

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <nav
            class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
          >
            <!-- Sidebar Toggle (Topbar) -->
            <button
              id="sidebarToggleTop"
              class="btn btn-link d-md-none rounded-circle mr-3"
            >
              <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Search -->
            <form
              class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
            >
              <div class="input-group">
                <input
                  type="text"
                  class="form-control bg-light border-0 small"
                  placeholder="Search for..."
                  aria-label="Search"
                  aria-describedby="basic-addon2"
                />
                <div class="input-group-append">
                  <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                  </button>
                </div>
              </div>
            </form>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
              <!-- Nav Item - Search Dropdown (Visible Only XS) -->
              <li class="nav-item dropdown no-arrow d-sm-none">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="searchDropdown"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div
                  class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                  aria-labelledby="searchDropdown"
                >
                  <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                      <input
                        type="text"
                        class="form-control bg-light border-0 small"
                        placeholder="Search for..."
                        aria-label="Search"
                        aria-describedby="basic-addon2"
                      />
                      <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                          <i class="fas fa-search fa-sm"></i>
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </li>

              <div class="topbar-divider d-none d-sm-block"></div>

              <!-- Nav Item - User Information -->
              <li class="nav-item dropdown no-arrow">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="userDropdown"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <span class="mr-2 d-none d-lg-inline text-gray-600 small"
                    >{{current_user.username | title}}</span
                  >
                  <img
                    class="img-profile rounded-circle"
                    src="{{url_for('static', filename='images/undraw_profile.svg')}}"
                  />
                </a>
                <!-- Dropdown - User Information -->
                <div
                  class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                  aria-labelledby="userDropdown"
                >
                  <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                  </a>
                  <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                  </a>
                  <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                  </a>
                  <div class="dropdown-divider"></div>
                  <a
                    class="dropdown-item"
                    href="{{url_for('auth.logout')}}"
                    data-toggle="modal"
                    data-target="#logoutModal"
                  >
                    <i
                      class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"
                    ></i>
                    Logout
                  </a>
                </div>
              </li>
            </ul>
          </nav>
          <!-- End of Topbar -->

          <!-- Body Content -->
          {% block content %}
          
          {% endblock %}

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; M-Thamini 2022</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            Select "Logout" below if you are ready to end your current session.
          </div>
          <div class="modal-footer">
            <button
              class="btn btn-secondary"
              type="button"
              data-dismiss="modal"
            >
              Cancel
            </button>
            <a class="btn btn-primary" href="{{url_for('auth.logout')}}">Logout</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{{url_for('static', filename='vendor/jquery/jquery.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js')}}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{url_for('static', filename='js/sb-admin-2.min.js')}}"></script>

    <!-- Page level plugins -->
    <script src="{{url_for('static', filename='vendor/chart.js/Chart.min.js')}}"></script>

    <!-- Page level custom scripts -->
    <script src="{{url_for('static', filename='js/demo/chart-area-demo.js')}}"></script>
    <script src="{{url_for('static', filename='js/demo/chart-pie-demo.js')}}"></script>
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
  </body>
</html>

app/templates/dash2.html
{% extends "base_dash.html" %}

{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">
  <!-- Page Heading -->
  <div
    class="d-sm-flex align-items-center justify-content-between mb-4"
  >
    <h1 class="h3 mb-0 text-gray-800">
      Welcome {{current_user.username | title}} To Your Dashboard
    </h1>
    <a
      href="{{ url_for('main.report_pdf', name=name) }}"
      class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"
      ><i class="fas fa-download fa-sm text-white-50"></i> Generate
      Valuation Report</a
    >
  </div>
  
  <a
  class="nav-link collapsed"
  href="{{url_for('main.assets_new',user_id=current_user.id)}}">

  <span class="xyz"><button class="btn btn-success new">Add New</button></span>
</a>
  

  <!-- Location Map -->
  <div class="map mt-5" style="max-width: 100%;">
  
  </div>
  <!-- Content Row -->
  <div class="row paragraph">
    <!-- ASSETS -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div
                class="text-xs font-weight-bold text-primary text-uppercase mb-1"
              >
                Total Fixed Assets
              </div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">
                KES. 24,463,000 
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-calendar fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Current Assets -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-success shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
           
            <div class="col mr-2">
              <div
                class="text-xs font-weight-bold text-success text-uppercase mb-1"
              >
                Total Current Assets
              </div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">
                KES. 2,038,200
              </div>
            </div>
            
            <div class="col-auto">
              <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Financial Assets -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-info shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div
                class="text-xs font-weight-bold text-info text-uppercase mb-1"
              >
                Total Financial Assets
              </div>
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <div
                    class="h5 mb-0 mr-3 font-weight-bold text-gray-800"
                  >
                    KES. 7,000,000
                  </div>
                </div>
                <div class="col">
                  <div class="progress progress-sm mr-2">
                    <div
                      class="progress-bar bg-info"
                      role="progressbar"
                      style="width: 50%"
                      aria-valuenow="50"
                      aria-valuemin="0"
                      aria-valuemax="100"
                    ></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-auto">
              <i
                class="fas fa-clipboard-list fa-2x text-gray-300"
              ></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-warning shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div
                class="text-xs font-weight-bold text-warning text-uppercase mb-1"
              >
                Total Net Worth
              </div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">
                KES. 33,501,200
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-comments fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Table Data -->
 

  <!-- Content Row -->

  <button class="btn btn-success show-chart m-4" id="reports">View/Hide Chart Reports</button>
  <div id="charts">
    <div class="row">
      <!-- Area Chart -->
      <div class="col-xl-8 col-lg-7 ">
        <div class="card shadow mb-4">
          <!-- Card Header - Dropdown -->
          <div
            class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
          >
            <h6 class="m-0 font-weight-bold text-primary">
              Net Worth Overview
            </h6>
            <div class="dropdown no-arrow">
              <a
                class="dropdown-toggle"
                href="#"
                role="button"
                id="dropdownMenuLink"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                <i
                  class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"
                ></i>
              </a>
              <div
                class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                aria-labelledby="dropdownMenuLink"
              >
                <div class="dropdown-header">Dropdown Header:</div>
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#"
                  >Something else here</a
                >
              </div>
            </div>
          </div>
          <!-- Card Body -->
          <div class="card-body">
            <div class="chart-area">
              <canvas id="myAreaChart"></canvas>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Pie Chart -->
      
      <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
          <!-- Card Header - Dropdown -->
          <div
            class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
          >
            <h6 class="m-0 font-weight-bold text-primary">
              Revenue Sources
            </h6>
            <div class="dropdown no-arrow">
              <a
                class="dropdown-toggle"
                href="#"
                role="button"
                id="dropdownMenuLink"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                <i
                  class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"
                ></i>
              </a>
              <div
                class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                aria-labelledby="dropdownMenuLink"
              >
                <div class="dropdown-header">Dropdown Header:</div>
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#"
                  >Something else here</a
                >
              </div>
            </div>
          </div>
          <!-- Card Body -->
          <div class="card-body">
            <div class="chart-pie pt-4 pb-2">
              <canvas id="myPieChart"></canvas>
            </div>
            <div class="mt-4 text-center small">
              <span class="mr-2">
                <i class="fas fa-circle text-primary"></i> Fixed Assets
              </span>
              <span class="mr-2">
                <i class="fas fa-circle text-success"></i> Financial Assets
              </span>
              <span class="mr-2">
                <i class="fas fa-circle text-info"></i> Current Assets
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.container-fluid -->
</div>



<!-- End of Main Content -->

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%} {% block content %}
<h1>Sorry, we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block content %}
<div class="intro-message text-center text-white my-5">
  <h2>About Our Product</h2>
  <p class="lead mx-auto fs-4 mt-3" style="max-width: 800px">
    M-Thamana is a web application that enables users to keep track of their
    assets in terms of land, houses, cars or shares and it generates for you a
    valuation report based on Pre-determined current market costs and analysis.
    In other words, <strong>don't guess your net worth, be sure of it</strong>
  </p>
</div>
<div>{% include "features.html" %}</div>
<section class="action p-4 text-center">
  <div class="container mx-auto subscribe">
    <div>
      <h2 class="fs-1">Ready To Start Managing Your Assets?</h2>
      <a href="{{url_for('auth.register')}}">
        <button class="btn btn-lg cta-btn mt-3">Get Started</button>
      </a>
    </div>
    <form
      class="form-inline ml-2"
      action="{{url_for('main.subscribe')}}"
      method="POST"
    >
      <h4>Subscribe To News Letter!</h4>
      <div class="md-form form-group">
        <label class="white-color">Enter your Email Address...</label>
        <input
          type="email"
          class="form-control mt-2"
          name="subscriber"
          required
        />
      </div>
      <div class="md-form mt-2 form-group">
        <button class="btn btn-sm cta-btn mx-auto" id="subs">Subscribe</button>
      </div>
    </form>
  </div>
</section>
{% endblock %}

app/templates/locations.html
{% extends "base_dash.html" %}
<iframe
  src="https://www.google.com"
  width="1200"
  height="600"
  style="border: 0"
  allowfullscreen=""
  loading="lazy"
  referrerpolicy="no-referrer-when-downgrade"
></iframe>

app/templates/tables.html
{% extends "base_dash.html" %}

<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <meta charset="utf-8" />
  </head>
  <link
    rel="stylesheet"
    href="{{url_for('static',filename='css/styles.css')}}"
  />
  <body>
    {% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">
      <a
        href="{{ url_for('main.report_pdf', name=name) }}"
        class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"
        ><i class="fas fa-download fa-sm text-white-50"></i> Generate Valuation
        Report</a
      >
      <!-- Page Heading -->
      <h1 class="h3 mb-2 text-gray-800">List of Assets Tables</h1>

      <!-- DataTales Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Available Assets</h6>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table
              class="table table-bordered"
              id="dataTable"
              width="100%"
              cellspacing="0"
            >
              <thead>
                <tr>
                  <th>Asset Name</th>
                  <th>Asset Description</th>
                  <th>Location</th>
                  <th>Asset Type</th>
                  <th>Date Acquired</th>
                  <th>Asset Value</th>
                </tr>
              </thead>

              <tbody>
                {% for post in posts %}

                <tr>
                  <td>{{post.assetname}}</td>
                  <td>{{post.description}}</td>
                  <td>{{post.location}}</td>
                  <td>{{post.category_id}}</td>
                  <td>{{post.date_posted.strftime('%d-%m-%Y')}}</td>
                  <td>KES.{{post.worth}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    {% endblock %}
  </body>
</html>